
version: "2"

services:
  backups:
    image: myros/mysql-backup
    volumes:
      - ~/backups/mysql:/backups

    environment:
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_PORT: 3306
      MYSQL_HOST: mysql
      # MYSQL_DB: wp_test_1; wp_test_2
      MYSQL_EXTRA_OPTS: --opt -v
      SCHEDULE: "@every 1h"
      SLACK_CHANNEL: "backups"
      SLACK_HOST: "https://hooks.slack.com/services/YOUR_DATA"

networks:
  default:
    external:
      name: maginfo
